name: Release

on:
  push:
    branches:
      - master
      - prerelease

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: install dependencies
        run: npm ci

      - name: Create Release Pull Request
        id: changeset_action
        uses: changesets/action@v1
        with:
          publish: npm run release_packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
